[program:clone-worker]
command=/opt/shopware-live-clone/run-console.sh messenger:consume async low_priority --time-limit=3600 --memory-limit=256M
directory=/var/lib/shopware-clone/source
user=dockware
numprocs=2
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
startsecs=3
startretries=10
stopwaitsecs=60
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/lib/shopware-clone/worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=2
